### ISSUE TITLE
Erro in javascript file

### ISSUE THREAD

**Issue by ghost** [IG-Group/swagger-search#1]
Hi.

I´m trying to use this project in my home, but when I play it I´m receiving the following error

TypeError: a.list is undefined.

d/this.getItemSource http://localhost:7878/js/list.min.js:1:9548
d http://localhost:7878/js/list.min.js:1:9098
d http://localhost:7878/js/list.min.js:1:11489
[8]</b.exports http://localhost:7878/js/list.min.js:1:11523
start http://localhost:7878/js/list.min.js:1:1375
o http://localhost:7878/js/list.min.js:1:3448
<anonymous> http://localhost:7878/search:117:23

I configured the swagger.config.edn just discommenting the "server-list" parameter.

Could you please check this error?

Tnks

**Comment by dlebrero** [comment]
Fixed in 0.5.2. 

I also noticed that to make the "server-list" to show something you will need to configure also the "possible-swagger-doc-suffix" parameter as [""]. 

See https://github.com/IG-Group/swagger-search/commit/82d828e7fe1ea036822c1ffc9f365ada4dc6b4e8
